INSTRUMENT_CHOICES = [
    'accordion',
    'acoustic guitar',
    'banjo',
    'bass guitar',
    'cajón',
    'cello',
    'clarinet',
    'dobro',
    'double bass',
    'drums',
    'flute',
    'harmonica',
    'harp',
    'keyboard',
    'lead guitar',
    'mandolin',
    'other',
    'other percussion',
    'piano',
    'rhythm guitar',
    'saxophone',
    'steel guitar',
    'trombone',
    'trumpet',
    'turntable',
    'ukulele',
    'violin',
    'viola',
    'vocals'
]

GENRE_CHOICES = [
    'acoustic',
    'alternative',
    'alt metal',
    'americana',
    'bluegrass',
    'blues',
    'calypso',
    'celtic',
    'christian/gospel',
    'classic rock',
    'classical',
    'country',
    'dance',
    'dubstep',
    'electronic',
    'folk',
    'funk',
    'hip hop',
    'jazz',
    'latin',
    'lounge',
    'metal',
    'other',
    'pop',
    'progressive',
    'punk',
    'r&b',
    'raggae',
    'rock',
    'rockabilly',
    'ska',
    'southern rock'
]